### PR TITLE
changed option 'cssprefix' to 'classPrefix'

### PR DESCRIPTION
**Pull request by mahnunchik**

### CODE REVIEW

**Comment by mbarlock** [comment]
+1 Can we get this merged?

**Comment by mahnunchik** [comment]
https://github.com/doctyper/gulp-modernizr/issues/20

**Comment by johnraz** [comment]
:+1: @doctyper any chance to get this merged ?

**Comment by johnraz** [comment]
well my bad, this one should be close and #16 should be merged instead

**Pull request closed without merging**
